<?
$largeImage = $this->recordImage($this->record($this->driver))->getLargeImage($this->index, ['w' => 1200, 'h' => 1200, 'maxh' => 1200]);
$originalImage = $this->recordImage($this->record($this->driver))->getLargeImage($this->index, ['bg' => null]);
$currentImage = $this->index+1;
$numOfImages = $this->record($this->driver)->getNumOfRecordImages('large');
?>
<? $unprocessedFormats = $this->driver->tryMethod('getUnprocessedFormats'); ?>
<? $format = $this->driver->getRecordType(); ?>
<div class="imagepopup-holder <?= $format ?>" data-type="<?= $format ?>" data-id="<?= $this->driver->getUniqueID() ?>">
  <div class="imagepopup-container">
    <div class="image iconlabel format-<?=$this->record($this->driver)->getFormatClass(end($unprocessedFormats))?>">
      <img src="<?= $largeImage ?>" />
    </div>
    <div class="content">
      <h3 class="title"><?= $this->escapeHtml($this->driver->getTitle()) ?></h3>
      <div class="author-and-dates">
        <p>
          <? if ($author = $this->driver->getPrimaryAuthor()): ?>
          <?= $this->escapeHtml($author) ?>
          <? endif; ?>
          <? foreach ($this->driver->getPublicationDates() as $date): ?>
          <?= $this->escapeHtml($date) ?>
          <? endforeach ?>
        </p>
      </div>
      <? if ($building = $this->driver->getBuilding()): ?>
      <div class="building"><?=$building[0] ?></div>
      <? endif ?>
      <div class="summary">
        <? if ($format == 'marc'): ?>
        <div>
        </div>
        <? else: ?>
           <? if ($summary = $this->driver->getSummary()): ?>
             <? foreach ($this->driver->getSummary() as $item): ?>
             <p><?= $this->escapeHtml($item) ?></p>
             <? endforeach ?>
          <? endif ?>
        <? endif ?>
      </div>
      <div class="record-link"><a href="<?= $this->recordLink()->getUrl($this->driver) ?>"><i class="fa fa-arrow-right"></i><?= $this->translate('To the record') ?></a></div>
      <? $rights = $this->driver->getImageRights($this->layout()->userLang) ?>
      <div class="image-info">
        <div class="record-index"><?= $this->translate('Record') ?> <span class="index"></span>/<span class="total"></span></div>
        <? if ($numOfImages > 1): ?>
        <div class="image-index"><?= $this->translate('Image') . " $currentImage/$numOfImages" ?></div>
        <? endif; ?>
        <div class="open-link"><a target="_blank" href="<?= $originalImage ?>"><i class="fa fa-new-window"></i></a></div>
      </div>

      <div class="image-rights">
        <div class="rights">
          <? $hasLink = isset($rights['link']); ?>
          <span><?= $this->translate("Image Rights") ?>:</span> <? if (isset($rights['copyright'])) : ?><? if ($hasLink): ?><a target="_blank" href="<?= $rights['link'] ?>"><? endif; ?><?= $this->transEsc($rights['copyright']) ?><? if ($hasLink): ?></a><? endif ?><? endif ?>
        </div>
        <div class="more-link copyright-link"><a data-mode="1" href=""><?= $this->translate('show_more') ?><i class="fa fa-arrow-down"></i></a></div>
        <div class="copyright">
          <? if (isset($rights['description'])): ?>
            <? foreach ($rights['description'] as $item): ?>
            <p><?= $this->transEsc($item) ?></p>
            <? endforeach ?>
          <? endif ?>
          <? if (!isset($rights['copyright']) && !isset($rights['description'])): ?>
            <p><?= $this->translate('Image Rights Default') ?>
            <p><a href="<?= $this->url('content-page', array('page' => 'terms_conditions')) . '#image_rights' ?>"><i class="fa fa-arrow-right"></i><?= $this->translate('See also terms and conditions') ?></a>
          <? endif; ?>

        </div>
        <div class="less-link copyright-link"><a data-mode="0" href=""><?= $this->translate('show_less') ?><i class="fa fa-arrow-up"></i></a></div>

      </div>
      <div style="clear: both;"></div>
    </div>
    <div style="clear: both;"></div>
  </div>
</div>
