<?
$largeImage = $this->recordImage($this->record($this->driver))->getLargeImage($this->index, ['w' => 1200, 'h' => 1200]);
$originalImage = $this->recordImage($this->record($this->driver))->getLargeImage($this->index);
$currentImage = $this->index+1;
$numOfImages = $this->record($this->driver)->getNumOfRecordImages('large');
?>
<? $formats = $this->driver->tryMethod('getFormats'); ?>
<? $translatedFormat = $this->transEsc(end($formats)); ?>
<? $recordType = $this->driver->getRecordType(); ?>
<div class="imagepopup-holder <?=$this->escapeHtmlAttr($recordType) ?>" data-type="<?=$this->escapeHtmlAttr($recordType) ?>" data-id="<?=$this->escapeHtmlAttr($this->driver->getUniqueID()) ?>">
  <div class="imagepopup-container">
    <div class="image iconlabel format-<?=$this->record($this->driver)->getFormatClass(end($formats))?>">
      <img src="<?= $largeImage ?>" />
    </div>
    <div class="content">
      <h3 class="title"><?= $this->escapeHtml($this->driver->getTitle()) ?></h3>
      <div class="author-and-dates">
        <? if ($recordType != 'lido'): ?>
          <p>
          <? if ($author = $this->driver->getPrimaryAuthor()): ?>
            <?= $this->escapeHtml($author) ?>
            <? endif; ?>
            <? if ($dates = $this->driver->trymethod('getResultDateRange')): ?>
              <?=$this->escapeHtml($dates[0]);?><? if (isset($dates[1]) && $dates[1] != $dates[0]): ?>&ndash;<?=$this->escapeHtml($dates[1])?><? endif; ?>
          <? else: ?>
            <? foreach ($this->driver->getPublicationDates() as $date): ?>
            <?= $this->escapeHtml($date) ?>
            <? endforeach ?>
          <? endif; ?>
          </p>
        <? else: ?>
            <? if ($results = $this->driver->getNonPresenterAuthors()): ?>
              <div class="truncate-field">
              <? foreach($results as $index => $author): ?>
                <?=($index > 0 ? '; ' : '')?><?=$this->escapeHtml($author['name'])?><? if (!empty($author['role'])): ?>, <?=$this->escapeHtml($author['role'])?><? endif; ?>
              <? endforeach; ?>
              <? if ($dates = $this->driver->getResultDateRange()): ?>
                <?=$this->escapeHtml($dates[0]);?><? if (isset($dates[1]) && $dates[1] != $dates[0]): ?>&ndash;<?=$this->escapeHtml($dates[1])?><? endif; ?>
              <? endif; ?>
              <? if ($results = $this->driver->getSubjectDates() && !isset($dates[0])): ?>
                <?=implode('<br/>', array_map(array($this, 'escapeHtml'), $results))?>
              <? endif; ?>
              </div>
            <? endif; ?>
        <? endif; ?>
      </div>
      <? $results = $this->driver->getInstitutions(); ?>
      <? if (count($results)): ?>
        <div class="building">
        <? foreach($results as $index => $institution): ?>
          <?=($index > 0 ? '<br/>' : '')?><?=$this->transEsc("source_$institution", array(), $this->translate($institution))?>
        <? endforeach; ?>
        </div>
      <? endif ?>
      <div class="summary loading">
        <div data-rows="6" class="truncate-field">
        <? if ($recordType == 'marc'): ?>
          <p></p>
        <? else: ?>
          <? if ($summary = $this->driver->getSummary()): ?>
            <? foreach ($this->driver->getSummary() as $item): ?>
              <p><?=preg_replace('/&lt;br\/?&gt;/', '<br>', $this->escapeHtml($item)) /* Allow <br> tag */ ?></p>
            <? endforeach ?>
          <? endif ?>
        <? endif ?>
        </div>
      </div>
      <? if ($listNotes): ?>
        <div class="list-notes">
          <strong><?= $this->translate('Description'); ?></strong><? if ($listUser): ?><span class="notes-user"> (<?=$this->escapeHtml(trim($this->userPublicName($this->listUser)))?>)</span><? endif; ?>:
          <ul>
          <? foreach ($listNotes as $note): ?>
            <li><?= preg_replace("/\r\n|\r|\n/",'<br>', $this->escapeHtml($note)) ?></li>
          <? endforeach; ?>
          </ul>
        </div>
      <? endif; ?>
          <div class="popup-link-buttons">
          <?
            $urls = $this->driver->getURLs();
            $onlineURLs = $this->driver->getOnlineURLs();
            $mergedData = $this->driver->tryMethod('getMergedRecordData');
            $images = array_keys($this->driver->getAllThumbnails('large'));
            $images = array_merge($images, array_keys($this->driver->getAllThumbnails('thumb')));
          ?>
          <? if (!empty($urls) || !empty($onlineURLs) || !empty($mergedData['urls'])): ?>
              <? $index = 0; ?>
                <? $renderedURLs = []; ?>
                <? if (!empty($urls)): ?>
                  <? foreach ($urls as $url): ?>
                    <?
                      $renderedURLs[] = $url['url'];
                      $desc = isset($url['desc']) ? $url['desc'] : $this->truncateUrl($url['url']);
                    ?>
                    <div class="record-online-link"><a href="<?=$this->escapeHtmlAttr($this->proxyUrl($url['url'])) ?>" target="_blank" title="<?=$this->escapeHtmlAttr($url['url']) ?>"><i class="fa fa-external-link"></i> <? if (count($urls) == 1): ?>  <?=$this->transEsc('open_online_link', ['%%format%%' => $translatedFormat])?><? else: ?><?=$this->transEsc('default::link_' . $desc, null, $desc) ?><? endif; ?></a></div>
                    <? if (strpos($this->escapeHtmlAttr($this->proxyUrl($url['url'])), 'vimeo.com') !== false): ?>
                    <? $vimeoId = filter_var($this->proxyUrl($url['url']), FILTER_SANITIZE_NUMBER_INT);?>
                    <script>
                      $('.imagepopup-container .image').html('<iframe src="https://player.vimeo.com/video/<?=$vimeoId?>?autoplay=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="display: inline-block;position:relative;max-width: 100%;width: 540px;height: 310px"></iframe><p><a href="https://vimeo.com/85437924"></a></p>');
                    </script>
                    <? endif; ?>
                    <? if (strpos($this->escapeHtmlAttr($this->proxyUrl($url['url'])), 'youtube.com') !== false): ?>
                    <? $youtubeId = explode("watch?v=",$this->proxyUrl($url['url']))[1];?>
                    <script>
                      $('.imagepopup-container .image').html('<iframe width="560" height="315" src="https://www.youtube.com/embed/<?=$youtubeId;?>?autoplay=1" frameborder="0" allowfullscreen style="display: inline-block;position:relative;max-width: 100%;width: 540px;height: 310px">></iframe></iframe>');
                    </script>
                    <? endif; ?>
                    <? $index++; ?>
                    <? if ($index > 4): ?>
                    <div>...</div>
                    <? break; endif; ?>
                  <? endforeach; ?>
                <? endif; ?>
                <? if (!empty($onlineURLs) || !empty($mergedData['urls'])): ?>
                  <? foreach (!empty($mergedData['urls']) ? $mergedData['urls'] : $onlineURLs as $url): ?>
                    <? if (in_array($url['url'], $images) || in_array($url['url'], $renderedURLs)) { continue; } ?>
                    <div class="record-online-link"><a href="<?=$this->escapeHtmlAttr($this->proxyUrl($url['url'])) ?>" target="_blank" title="<?=$this->escapeHtmlAttr($url['url']) ?>"><i class="fa fa-external-link"></i><? if (count($onlineURLs) == 1 || count($mergedData['urls']) == 1): ?> <?=$this->transEsc('open_online_link', ['%%format%%' => $translatedFormat])?><? else: ?><?=!empty($url['text']) ? $this->transEsc('default::link_' . $url['text'], null, $url['text']) : $this->escapeHtml($this->truncateUrl($url['url'])) ?><? endif; ?></a>
                    <? if ($url['source']): ?>
                      <span class="online-source"><?=is_array($url['source']) ? '('.$this->transEsc('Multiple Organisations').')' : '';?></span>
                    <? endif; ?>
                    </div>
                  <? endforeach; ?>
                <? endif; ?>
          <? endif; ?>
          <div class="record-link"><a href="<?= $this->recordLink()->getUrl($this->driver) ?>"><i class="fa fa-arrow-right"></i><?= $this->translate('To the record') ?></a></div>
          <? $rights = $this->driver->getImageRights($this->layout()->userLang) ?>
          <div class="save-record-link"><a href="<?=$this->recordLink()->getActionUrl($this->driver, 'Save')?>" class="save-record" data-lightbox data-id="<?=$this->escapeHtmlAttr($this->driver->getUniqueId()) ?>" title="<?=$this->transEsc('Add to favorites')?>"><i class="fa fa-heart"></i> <?=$this->transEsc('Add to favorites')?></a></div>
          <div class="open-link"><a target="_blank" href="<?= $originalImage ?>"><i class="fa fa-download"></i> <?= $this->translate('Show image in new window') ?></a> <span class="image-dimensions"></span></div>

        </div>
        <? if (in_array($recordType, ['ead', 'lido', 'qdc'])): ?>
        <div class="image-rights">
          <div class="rights">
            <? $hasLink = isset($rights['link']); ?>
            <span><?= $this->translate("Image Rights") ?>:</span> <? if (isset($rights['copyright'])) : ?><? if ($hasLink): ?><a target="_blank" href="<?= $rights['link'] ?>"><? endif; ?><?= $this->transEsc($rights['copyright']) ?><? if ($hasLink): ?></a><? endif ?><? endif ?>
          </div>
          <div class="more-link copyright-link"><a data-mode="1" href=""><?= $this->translate('show_more') ?><i class="fa fa-arrow-down"></i></a></div>
          <div class="copyright">
            <? if (isset($rights['description'])): ?>
              <? foreach ($rights['description'] as $item): ?>
              <p><?= $this->transEsc($item) ?></p>
              <? endforeach ?>
            <? endif ?>
            <? if (!isset($rights['copyright']) && !isset($rights['description'])): ?>
              <p><?= $this->translate('Image Rights Default') ?>
              <p><a href="<?= $this->url('content-page', array('page' => 'terms_conditions')) . '#image_rights' ?>"><i class="fa fa-arrow-right"></i><?= $this->translate('See also terms and conditions') ?></a>
            <? endif; ?>
          </div>
          <div class="less-link copyright-link"><a data-mode="0" href=""><?= $this->translate('show_less') ?><i class="fa fa-arrow-up"></i></a></div>
          <? if ($this->resolver('record/record-organisation-menu.phtml')): ?>
            <?=$this->render('record/record-organisation-menu.phtml') ?>
          <? endif; ?>
        </div>
      <? endif; ?>
      <div style="clear: both;"></div>
    </div>
    <div class="image-info">
        <? if ($numOfImages > 1): ?>
        <div class="image-index"><?= $this->translate('Image') . " $currentImage / $numOfImages" ?></div>
        <? endif; ?>
        <div class="record-index"><span class="index"></span> / <span class="total"></span></div>
    </div>
    <div style="clear: both;"></div>
  </div>
  <?
    // NOTE: Piwik js-script must be inserted inside an element (not at the template root).
    // Otherwise Magnific popup close button gets appended to the script tag which causes a js-error...
  ?>
  <?=
  $this->piwik([
    'lightbox' => true, 'record' => $this->driver, 'action' => 'imagePopup',
    'recordUrl' => $this->recordLink()->getUrl($this->driver)
  ]);
  ?>
</div>
